# fork fscarmen
name: "Build and push images"

on:
  workflow_dispatch:

jobs:
  Building:
      runs-on: ubuntu-latest
      name: "Build Xray images"
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKERHUB_REPOSITORY: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest

      steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to DockerHub
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push images to Docker hub
        uses: docker/build-push-action@v2.9.0
        with:
          push: true
          platforms: linux/amd64
          tags: ${{ env.DOCKERHUB_REPOSITORY }}
